spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
server:
  port: 8081

env: dev
  
---
spring:
  profiles: prod
  jpa:
    show-sql: true
    database: mysql
    generate-ddl: true
  datasource:
    url: jdbc:mysql://db:3306/Todo
    username: ${DB_USER}
    password: ${DB_PASSWORD} 
env: prod
    
server:
  port: 8080
 